[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/fourier",
    "crates/waveguide",
    "crates/cwt",
    "crates/visualizer",
    "crates/io",           
    "crates/geom_builder", 
    "crates/phc",
]
