[package]
name = "geom_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
io = { path = "../io" }
ndarray = "0.15.6"
log = "0.4"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.3.20"