[package]
name = "pc_fourier"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = "0.4"
pc_core = { path = "../pc_core" }
ndarray = "0.17.1"        # <-- ADD THIS  
rustfft = "6.1"         # <-- ADD THIS (required by ndarray-fft)
# scilib is no longer needed