[package]
name = "pc_cwt"
version = "0.1.0"
edition = "2021"

[dependencies]
pc_core = { path = "../pc_core" }
pc_fourier = { path = "../pc_fourier" }
pc_waveguide = { path = "../pc_waveguide" }
ndarray = "0.16"

